### ISSUE TITLE
winserver 2012 r2 'vuln_scan_res' 

### ISSUE THREAD

**Issue by JimLeon595** [chroblert/SecurityBaselineCheck#4]
```
Internal Server Error: /baseline/windows_scan_res_report/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Django-3.0.4-py3.6.egg/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/Django-3.0.4-py3.6.egg/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/Django-3.0.4-py3.6.egg/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/Django-3.0.4-py3.6.egg/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/root/AssetManage/baseline/views.py", line 140, in windows_scan_res_report
    windowsVulnScanResDict=windowsScanResDict['vuln_scan_res']
KeyError: 'vuln_scan_res'
[18/Dec/2020 16:11:20] "POST /baseline/windows_scan_res_report/ HTTP/1.1" 500 71936                                                                     
[18/Dec/2020 16:11:38] "GET /baseline/scan_res_display/ HTTP/1.1" 200 15635
Internal Server Error: /baseline/windows_scan_res_report/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Django-3.0.4-py3.6.egg/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/Django-3.0.4-py3.6.egg/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/Django-3.0.4-py3.6.egg/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/Django-3.0.4-py3.6.egg/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/root/AssetManage/baseline/views.py", line 140, in windows_scan_res_report
    windowsVulnScanResDict=windowsScanResDict['vuln_scan_res']
KeyError: 'vuln_scan_res'
[18/Dec/2020 16:22:09] "POST /baseline/windows_scan_res_report/ HTTP/1.1" 500 71933 
```
注释掉输出代码可以本地输出，但是不能上传到后台去

**Comment by JimLeon595** [comment]
```
Invoke-RestMethod : KeyError at /baseline/windows_scan_res_report/
'vuln_scan_res'Request Method:POST
Request URL:http://192.168.10.15:8000/baseline/windows_scan_res_report/
Django Version:3.0.4
Exception Type:KeyError
Exception Value:'vuln_scan_res'
Exception Location:/root/AssetManage/baseline/views.py in windows_scan_res_report, line 140
Python Executable:/usr/local/bin/python
Python Version:3.6.10
Python Path:['/root/AssetManage',
 '/usr/local/lib/python36.zip',
 '/usr/local/lib/python3.6',
 '/usr/local/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/site-packages',
 '/usr/local/lib/python3.6/site-packages/Django-3.0.4-py3.6.egg',
 '/usr/local/lib/python3.6/site-packages/asgiref-3.2.5-py3.6.egg',
 '/usr/local/lib/python3.6/site-packages/sqlparse-0.3.1-py3.6.egg',
 '/usr/local/lib/python3.6/site-packages/pytz-2019.3-py3.6.egg']
```

**Comment by chroblert** [comment]
该项目已转移到https://github.com/chroblert/AssetManage/tree/master/Agent
